name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  # --------------------- CI: Install + Tests -----------------------
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"   # <-- UPDATED

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Add project to Python path
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Checkout with LFS
      uses: actions/checkout@v3
      with:
        lfs: true


    - name: Run tests
      run: |
        pip install pytest
        pytest -q

  # --------------------- CI: Docker Build Test ---------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image (test only)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: false

  # --------------------- CD: Deploy to Google Cloud Run ---------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    # Authenticate with your service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: "${{ secrets.GCP_PROJECT }}"
        export_default_credentials: true

    # Build & Push to Artifact Registry
    - name: Build & Push to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-app/ml-api .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-app/ml-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ml-api \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/ml-app/ml-api \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
